### ISSUE TITLE
Rust RFC - 021 Projections API  Implementation

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStoreDB-Client-Rust#101]
@tambeau commented on [Fri Nov 05 2021](https://github.com/EventStore/home/issues/660)

Implementation of State Operations for Rust gRPC Projections API

State
- [ ] Get Query (Name, Config?) **blocked - Server Update Required**
- [ ] Get Config (Name) **blocked - Server Update Required**
- [x] Get Status (Name) **blocked - Server Update Required**
- [x] Get State (Name, Partition)  **missing partition option**
- [x] Get Result (Name, Partition) **blocked**

Statistics
- [x] Get Statistics (name)
- [x] List All
- [x] List

Create
- [x] Create Projection (Name, Query, EmitEnabled, TrackEmittedStreams) - Enabled parameter remove always set to false

Update
- [x] Projection (Name, Query, EmitEnabled)
- [ ] Config (Name, Config)

**Comment by YoEight** [comment]
Done a long time ago
