### ISSUE TITLE
Increase max receive message length to match the max event size in EventStoreDB

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStoreDB-Client-Rust#127]
EventStoreDB allows events up to 16mb in size so the gRPC clients need to be able to read events this large.

**Comment by YoEight** [comment]
I can't see any settings that can allow this in the underlying `http2` library

**Comment by josephcummings** [comment]
Going to take a look at this after discussing with @YoEight

We should be able to configure `max_encoding_message_size` and `max_decoding_message_size` on the generated tonic clients, which was introduced in the last year in https://github.com/hyperium/tonic/pull/1274

The default in tonic, as per that PR, is now 4mb
