### ISSUE TITLE
ClientSettings parse - allow underscore for hostname

### ISSUE THREAD

**Issue by jsiefer** [EventStore/EventStoreDB-Client-Rust#164]
Can we allow underscore _ for host names when parsing settings string? Quite commonly used when using docker compose i think. 

e.g.
`esdb://foo:bar@eventstore_db:2113`

**Comment by YoEight** [comment]
Are you sure? I see everywhere that `_` are prohibited

**Comment by YoEight** [comment]
`url` crate seems to accept `_` indeed:

```rust
let is_invalid_host_char = |c| {
            matches!(
                c,
                '\0' | '\t'
                    | '\n'
                    | '\r'
                    | ' '
                    | '#'
                    | '/'
                    | ':'
                    | '<'
                    | '>'
                    | '?'
                    | '@'
                    | '['
                    | '\\'
                    | ']'
                    | '^'
                    | '|'
            )
        };
```

**Comment by jsiefer** [comment]
I think this part caused problems for me - inside the parsing function for ClientSettings

https://github.com/EventStore/EventStoreDB-Client-Rust/blob/15abe4006ee9f2e5ca4250756df5bc3daf34d53d/eventstore/src/grpc.rs#L361

**Comment by jsiefer** [comment]
You are right. Looks like underscores are not allowed in domain names. I only stumbled on it when I was using docker and used an underscore in the service name.

Should (can) parsing fail then instead of falling back to default values?

**Comment by YoEight** [comment]
Hey @jsiefer,

PR #169 supports underscore in hostname and gossip seeds and also fixes the issue you mentioned.

**Comment by jsiefer** [comment]
thank you!
