### ISSUE TITLE
Creating json eventdata from str/byte 

### ISSUE THREAD

**Issue by jsiefer** [EventStore/EventStoreDB-Client-Rust#167]
I would be nice if one could construct _json EventData_ from already made json.

e.g.
`eventstore::EventData::json_str()`

**Comment by YoEight** [comment]
Hey @jsiefer,

You can achieve that already by using `serde_json::RawValue`. I think you might find that function useful: https://docs.rs/serde_json/1.0.107/serde_json/value/struct.RawValue.html#method.from_string

`serde_json::RawValue` implements `Serialize`

**Comment by jsiefer** [comment]
Right, good point! Thank you!
 (and sorry for the late reply)
