### ISSUE TITLE
EventData::json should take payload by shared reference

### ISSUE THREAD

**Issue by hseeberger** [EventStore/EventStoreDB-Client-Rust#180]
Currently the signature of `EventData::json` looks like this:

```rust
pub fn json<S, P>(event_type: S, payload: P) -> serde_json::Result<EventData>
```

The `payload` is later only used by shared reference, there is no need for an owned value:

```rust
let payload = Bytes::from(serde_json::to_vec(&payload)?);
```

Therefore the signature could be changed (notice `&P` instead of `P`):

```rust
pub fn json<S, P>(event_type: S, payload: &P) -> serde_json::Result<EventData>
```

This would avoid cloning the event in cases where it is needed after invoking `EventData::json`.

**Comment by YoEight** [comment]
It's now available on crates.io:  https://crates.io/crates/eventstore/4.0.0
