### ISSUE TITLE
Please change in Readme

### ISSUE THREAD

**Issue by codercengiz** [EventStore/EventStoreDB-Client-Rust#59]
when i want to connect with this connection string :
`let settings = "esdb://admin:changeit@localhost:2113".parse()?;`
there is a Error because my localhost (docker) is not secure and connectrionstring has default value tls=true. When man dont use logging system in Rust, man can not see what is the problem. When using the logging system in rust , the error is :
`ERROR eventstore::grpc] Error when connecting to https://localhost:2113/: transport error: error trying to connect: received corrupt message`

When you change the Readmefile , man can easily try Eventstoredb in his project. like this:

# Example

```rust
use eventstore::{ All, Client, EventData, ReadResult };
use futures::stream::TryStreamExt;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug)]
struct Foo {
    is_rust_a_nice_language: bool,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {

    // Creates a client settings for a single node configuration.
    let settings = "esdb://admin:changeit@localhost:2113?tls=false".parse()?;
    let client = Client::create(settings).await?;

    let payload = Foo {
        is_rust_a_nice_language: true,
    };

**Comment by YoEight** [comment]
Thanks @codercengiz  for your suggestion but we don't want to promote unsecured configurations on the README.md. I understand however the instructions were confusing for a local dev experience. I will clarify README.md instructions and add a link to the appropriate documentation.
